name: Build and Push Docker Image
on:
  push:
    branches:
      - container
jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: oduodg/munji-frontend:${{ github.sha }}
  # 
  # update Image tag to front-deploy.yaml
  #
    - name: Check out k8s repo
      uses: actions/chekout@master
      with:
        repository: munji-goorm/manifest
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
    - name: git push image tag to k8 repo
      run: ls -al
