name: Build and Push Docker Image
on:
  push:
    branches:
      - container
jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      env:
        REACT_APP_KAKAOMAP_API_KEY_JS=${{ secrets.REACT_APP_KAKAOMAP_API_KEY_JS }}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: oduodg/munji-frontend:${{ github.sha }}
  # 
  # update Image tag to front-deploy.yaml
  #
    - name: Git config
      run: |
        git config --global user.email "werewildfire@gmail.com"
        git config --global user.name "oduodg"
    - name: Check out k8s repo
      uses: actions/checkout@master
      with:
        repository: munji-goorm/manifest
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
        path: manifest
    - name: git push image tag to k8 repo
      run: |
        cd manifest
        sed -i "40 c\        image: oduodg/munji-frontend:${{ github.sha }}" front-deploy.yaml
        git add .
        git commit -m "Edit front image tag"
        git push -f --set-upstream origin main
