name: Build and Push Docker Image
on:
  push:
    branches:
      - prod-v2
jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v3

    - name: Generate Environment Variables File for Production
      run: |
        echo "REACT_APP_KAKAOMAP_API_KEY_JS=${{ secrets.REACT_APP_KAKAOMAP_API_KEY_JS }}">>.env.production
        echo "REACT_APP_KAKAOMAP_API_KEY_REST=${{ secrets.REACT_APP_KAKAOMAP_API_KEY_REST }}">>.env.production
        cat .env.production
        ls -al

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: munji-frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
  # 
  # update Image tag to front-deploy.yaml
  #
    - name: Git config
      run: |
        git config --global user.email "werewildfire@gmail.com"
        git config --global user.name "oduodg"
    - name: Check out k8s repo
      uses: actions/checkout@master
      with:
        repository: munji-goorm/manifest
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
        path: manifest
    - name: git push image tag to k8 repo
      run: |
        cd manifest
        sed -i "20 c\        image: 320451040304.dkr.ecr.ap-northeast-2.amazonaws.com/munji-frontend:${{ github.sha }}" front-deploy.yaml
        git add .
        git commit -m "Edit front image tag"
        git push -f --set-upstream origin main
